plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '1.0.0'
}

base {
    archivesName = "${mod_id}-${minecraft_version}"
}

version = "${mod_version}"

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = neoforge_version

    parchment {
        mappingsVersion = mapping_version
        minecraftVersion = mapping_minecraft
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        server {
            server()
            systemProperty "neoforge.enabledGameTestNamespaces", mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), --'existing', file('src/main/resources').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            logLevel = org.slf4j.event.Level.DEBUG
        }
    }


    sourceSets.main.resources { srcDir 'src/generated/resources' }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title': mod_id,
                'Specification-Vendor': "Mattéo",
                'Specification-Version': "1",
                'Implementation-Timestap': new Date().format("yyyy-MM-dd:mm:ssZ")
        ])
    }

    //finalizedBy 'reobfJar'
}

tasks.register('sourceJar', Jar) {
    dependsOn 'classes'
    from sourceSets.main.allSource
    archiveClassifier = 'sources'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}