plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.78'
}

base {
    archivesName = "${mod_id}-${minecraft_version}"
}

version = "${mod_version}"

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = neoforge_version

    parchment {
        mappingsVersion = mapping_version
        minecraftVersion = mapping_minecraft
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
        }

        server {
            server()
            systemProperty "neoforge.enabledGameTestNamespaces", mod_id
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    sourceSets.main.resources { srcDir 'src/generated/resources' }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    implementation "curse.maven:magic-coins-597281:6905939"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
                minecraft_version: minecraft_version,
                neoforge_version: neoforge_version,
                mod_id: mod_id,
                mod_version: mod_version,
        ]
        inputs.properties replaceProperties
        filesMatching(['META-INF/neoforge.mods.toml']) {
            expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}