org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# CONFIGS GENERAL
neo_version_range=[21.1.93,)
minecraft_version=1.21.1
loader_version_range=[4,)

mod_version=0.3
mod_id=playerbounty
mod_name=PlayerBounty
mod_license=MIT License
mod_authors=matteo35
mod_credits=SirGrantd
mod_description=Display a highly customizable bounty over the players head. Increasing and decreasing when players kill each other
logo_file = logo.png

sg_economy_version=1.0.2