org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# CONFIGS GENERAL
dev_forge_version=47.4.20
minimum_forge_version=[47.0.0,)
minecraft_version=1.20.1
loader_version_range=[47,)

mod_version=0.51
mod_id=playerbounty
mod_name=PlayerBounty
mod_license=MIT License
mod_authors=matteo35
mod_description=Display a highly customizable bounty over the players head. Increasing and decreasing when players kill each other
logo_file=logo.png

mapping_channel=parchment
mapping_version=2023.07.30-1.20.1