repositories {
    maven {
        name = 'CurseMaven'
        url "https://cursemaven.com"
    }

    maven { url = 'https://maven.100media.dev/' }
}

configurations {
    shade
    implementation.extendsFrom shade
}

dependencies {
    //Numismatic Overhaul Reforged Again
    implementation fg.deobf("curse.maven:numismatic-overhaul-reforged-again-1294551:7263660")
    //Create: Numismatics
    implementation fg.deobf("curse.maven:numismatics-889722:6264591")

    //Compat dependencies
    implementation "curse.maven:create-328085:7178761"
    shade "dev._100media.capabilitysyncer:capabilitysyncer:1.20.1-4.0.1"
}