repositories {
    maven {
        name = 'CurseMaven'
        url "https://cursemaven.com"
    }
}

dependencies {
    //Magic Coins support & SG_Economy API
    implementation "curse.maven:sg-economy-api-1446971:8041335"
    //Numismatic Overhaul Reforged Again
    implementation "curse.maven:numismatic-overhaul-reforged-again-1294551:6801648"
    //Create: Numismatics
    implementation "curse.maven:numismatics-889722:7948018"

    //Comapt dependencies
    implementation "curse.maven:owo-lib-532610:6785734"
    implementation "curse.maven:forgified-fabric-api-889079:7658611"
    implementation "curse.maven:create-328085:7963363"
}