modLoader="javafml"
loaderVersion="[46,)"
license = "MIT License"

[[mods]]
modId="playerbounty"
version="1.20.1-0.2"
displayName="Player Bounty"
authors = "Mattéo"
description= "Add a customization bounty system on players, nothing more"
logoFile= "logo.png"

[[dependencies.playerbounty]]
modId="forge"
mandatory=true
versionRange="[47.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.playerbounty]]
modId="minecraft"
mandatory=true
versionRange="1.20.1"
ordering="NONE"
side="BOTH"